"use strict";

// Shared userscript globals used across concatenated src/*.js fragments.
module.exports = {
  unsafeWindow: "readonly",
  GM: "readonly",
  GM_info: "readonly",
  GM_setValue: "readonly",
  GM_getValue: "readonly",
  GM_download: "readonly",
  GM_xmlhttpRequest: "readonly",
  PAGE_WINDOW: "readonly",
  TELEGRAM_PLUS_LOCALES: "readonly",

  // src/pure.js exports (consumed by other fragments)
  hashCode: "readonly",
  safeJsonParse: "readonly",
  isPlainObject: "readonly",
  SUPPORTED_MIMES: "readonly",
  DEFAULT_SETTINGS: "readonly",
  ALLOWED_DOWNLOAD_LOCATIONS: "readonly",
  ALLOWED_UI_LANGUAGES: "readonly",
  DEFAULT_LOCALE_ALIAS_MAP: "readonly",
  normalizeSettings: "readonly",
  getExtensionFromMime: "readonly",
  isValidMimeType: "readonly",
  extractFileName: "readonly",
  shouldRetryDownloadError: "readonly",
  getRetryDelayMs: "readonly",
  getRetryPlan: "readonly",
  getCancelPlan: "readonly",
  canManualRetry: "readonly",
  getQueueSlots: "readonly",
  planPendingSelection: "readonly",
  getQueueActivationIndexes: "readonly",
  detectBrowserLocaleCode: "readonly",
  normalizeLocaleCode: "readonly",
  translateDictionaryKey: "readonly",

  // Cross-module globals from src/*.js
  logger: "readonly",
  DOWNLOAD_ICON: "readonly",
  FORWARD_ICON: "readonly",
  contentRangeRegex: "readonly",
  REFRESH_DELAY: "readonly",
  MAX_NOTIFICATIONS: "readonly",
  MAX_ACTIVE_DOWNLOADS: "readonly",
  MAX_RETRIES: "readonly",
  RETRY_DELAY_BASE: "readonly",
  EAGER_DOWNLOAD_LIMIT: "readonly",
  SETTINGS_KEY: "readonly",
  SETTINGS_SCHEMA_VERSION: "readonly",
  PROGRESS_KEY: "readonly",
  PROGRESS_CONTAINER_ID: "readonly",
  TELEGRAM_SELECTORS: "readonly",
  IS_SAFARI: "readonly",
  storageAdapter: "readonly",
  storageCache: "readonly",
  loadSettings: "readonly",
  saveSettings: "readonly",
  state: "readonly",

  onDomReady: "readonly",
  appendToRoot: "readonly",
  applyStyles: "readonly",
  createElement: "readonly",
  debounce: "readonly",
  randomId: "readonly",
  getTheme: "readonly",
  triggerAnchorDownload: "readonly",
  openInNewTab: "readonly",
  openWithFallback: "readonly",
  setButtonIconContent: "readonly",
  styleFactory: "readonly",
  notificationFactory: "readonly",
  SETTINGS_PANEL_CSS: "readonly",

  i18n: "readonly",
  settingsBuilder: "readonly",
  settingsModule: "readonly",
  reportModule: "readonly",
  updateModule: "readonly",

  progressFactory: "readonly",
  showNotification: "readonly",
  showNotificationIfEnabled: "readonly",
  downloadCompatibility: "readonly",
  queueManager: "readonly",
  downloadsModule: "readonly",

  getText: "readonly",
  getActiveMediaContext: "readonly",
  getCandidateMediaUrl: "readonly",
  uiMediaButtons: "readonly",
  uiLauncher: "readonly",
  uiModule: "readonly",
  keyboardModule: "readonly",
  observersModule: "readonly",
  themeObserver: "readonly",
  safariSmokeMatrix: "readonly",
  selfTest: "readonly",
  init: "readonly",
};
